apiVersion: apps/v1
kind: Deployment
metadata:
  name: "micronaut-cafe"
spec:
  selector:
    matchLabels:
      app: "micronaut-cafe"
  template:
    metadata:
      labels:
        app: "micronaut-cafe"
    spec:
      containers:
        - name: "micronaut-cafe"
          image: "gcr.io/micronaut-cafe/jib-image"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
        - name: "postgres"
          image: "postgres:alpine"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: "micronaut-cafe"
spec:
  selector:
    app: "micronaut-cafe"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080