apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: micronaut-cafe
build:
  artifacts:
    - image: eu.gcr.io/tools-org-veroo/jib-image
      jib:
        type: gradle
deploy:
  kubectl:
    manifests:
      - k8s.yml
