apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: micronaut-cafe
build:
  artifacts:
    - image: gcr.io/micronaut-cafe/jib-image
      jib:
        type: gradle
deploy:
  kubectl:
    manifests:
      - k8s.yml
