micronaut:
  application:
    name: "micronautCafe"
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver: "className=org.postgresql.Driver"
    username: "postgres"
    password: "postgres"
    dialect: "POSTGRES"
    initialization-fail-timeout: 30
